# Site settings
title: UX Design portfolio for Daniel Lau
description: UX Design portfolio for Daniel Lau
keywords: Daniel Lau, UX, UXD, UXR, Product Management, UX Design, UX Research
author: Daniel Lau
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
